CREATE TABLE attraction (
    `id` int NOT NULL,
    `id_park` int,
    `id_univ` int,
    `name` VARCHAR(255),
    `slug` VARCHAR(255),
    `description` TEXT, 
    `restriction` VARCHAR (255), 
    `pictures` VARCHAR (255), 
    `movies` VARCHAR (255), 
    PRIMARY KEY (`id`),
    CONSTRAINT FK_AttractionPark FOREIGN KEY (`id_park`) REFERENCES park(`id`),
    CONSTRAINT FK_AttractionUnivers FOREIGN KEY (`id_univ`) REFERENCES univers(`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
INSERT INTO attraction (`id`,`id_park`,`id_univ`,`name`,`slug`,`description`,`restriction`,`pictures`,`movies`) VALUES
(1,1,1,'Adventure Isle','adventure-isle','Aventure en famille','Promenades relaxantes','adventure-isle.jpg','adventure-isle.avi'),
(2,1,3,'Alice\'s Curious Labyrinth','alice-s-curious-labyrinth','Divertissement pour les plus petits','Pas de restriction', 'alice-s-curious-labyrinth.jpg', 'alice-s-curious-labyrinth.avi'),
(3,1,2,'Autopia','autopia','Divertissement pour les plus petits','Taille: 0,80m','picture1.jpg','movie.avi'),
(4,1,4,'Big Thunder Mountain','big-thunder-mountain','Grands frissons','Taille: 1,02m','big-thunder-mountain.jpg','big-thunder-mountain.avi'),
(5,1,3,'Blanche-Neige et les Sept Nains','blanche-neige-et-les-sept-nains','Aventure en famille. Peut effrayer les plus petits','Pas de restriction','picture1.jpg','movie.avi'),
(6,1,2,'Buzz Lightyear Laser Blast','buzz-lightyear-last-blast','Aventure en famille','Pas de restriction','picture1.jpg','movie.avi'),
(7,1,5,'Discovery Arcade Main Street - USA','discovery-arcade-main-street-usa','Aventure en famille','Pas de restriction','picture1.jpg','movie.avi'),
(8,1,5,'Disneyland Railroad','disneyland-railroad','Divertissement pour les plus petits','Pas de restriction','picture1.jpg','movie.avi'),
(9,1,3,'Dumbo the Flying Elephant','dumbo-the-flying-elephant','Divertissement pour les plus petits','Pas de restriction','picture1.jpg','movie.avi'),
(10,1,4,'Frontierland Playground','frontierland-playground','Divertissement pour les plus petits','Pas de restriction','picture1.jpg','movie.avi'),
(11,1,5,'Horse-Drawn Streetcars','horse-drawn-streetcarts','Divertissement pour les plus petits','Pas de restriction','picture1.jpg','movie.avi'),
(12,1,1,'Indiana Jones et le Temple du Péril','indiana-jones-et-le-temple-du-peril','Grands frissons','Taille: 1,40m','picture1.jpg','movie.avi'),
(13,1,3,'It\'s a small world','its-a-small-world','Divertissement pour les plus petits','Pas de restriction','picture1.jpg','movie.avi'),
(14,1,1,'La Cabane des Robinson','la-cabane-des-robinson','Aventure en famille','Pas de restriction','picture1.jpg','movie.avi'),
(15,1,3,'La Galerie de la Belle au Bois Dormant','la-galerie-de-la-belle-au-bois-dormant','Aventure en Famille','Pas de restriction','picture1.jpg','movie.avi'),
(16,1,1,'Le Galion des Pirates','le-galion-des-pirates','Aventure en Famille','Pas de restriction','picture1.jpg','movie.avi'),
(17,1,1,'La Plage des Pirates','la-plage-des-pirates','Divertissement pour les plus petits','Pas de restriction','picture1.jpg','movie.avi'),
(18,1,3,'La Tanière du Dragon','la-taniere-du-dragon','Peut effrayer les plus petits','Pas de restriction','picture1.jpg','movie.avi'),
(19,1,3,'Le Carrousel de Lancelot','le-carrousel-de-lancelot','Divertissement pour les plus petits','Pas de restriction','picture1.jpg','movie.avi'),
(20,1,3,'Le Château de la Belle au Bois Dormant','le-chateau-de-la-belle-au-bois-dormant','Aventure en famille','Pas de restriction','picture1.jpg','movie.avi'),
(21,1,1,'Le Passage Enchanté d\'Aladdin','le-passage-enchanté-d-aladdin','Divertissement pour les plus petits','Pas de restriction','picture1.jpg','movie.avi'),
(22,1,3,'Le Pays des Contes de Fées','le-pays-des-contes-de-fees','Aventure','Pas de restriction','picture1.jpg','movie.avi'),
(23,1,2,'Les Mystères du Nautilus','les-mysteres-du-nautilus','Divertissement pour les plus petits','Pas de restriction','picture1.jpg','movie.avi'),
(24,1,3,'Les Voyages de Pinocchio','les-voyages-de-pinocchio','Aventure en famille. Peut effrayer les plus petits','Pas de restriction','picture1.jpg','movie.avi'),
(25,1,5,'Les jardins féériques 	Main Street, U.S.A','les-jardins-feeriques-de-main-street-usa','Aventure en famille. Peut effrayer les plus petits','Pas de restriction','picture1.jpg','movie.avi'),
(26,1,5,'Liberty Arcade','liberty-arcade','Promenades relaxantes','Pas de restriction','picture1.jpg','movie.avi'),
(27,1,3,'Mad Hatter\'s Tea Cups','mad-hatter-s-tea-cups','Aventure en famille','Pas de restriction','picture1.jpg','movie.avi'),
(28,1,5,'Main Street Vehicles','main-street-vehicles','Divertissement pour les plus petits. Promenades relaxantes','Pas de restriction','picture1.jpg','movie.avi'),
(29,1,2,'Mickey et son Orchestre PhilharMagique','mickey-et-son-orchestre-philharmagique','Les visiteurs peuvent etre eclabousses','Pas de restriction','picture1.jpg','movie.avi'),
(30,1,2,'Orbitron','orbitron','Divertissement pour les plus petits','Pas de restriction','picture1.jpg','movie.avi'),
(31,1,3,'Pavillon des Princesses','pavillon-des-princesses','Divertissement pour les plus petits.','Pas de restriction','picture1.jpg','movie.avi'),
(32,1,3,'Peter Pan\'s Flight','peter-pan-s-flight','Voyage à faire dès son plus jeune âge en famille','Pas de restriction','picture1.jpg','movie.avi'),
(33,1,4,'Phantom Manor','phantom-manor','Peut effrayer les plus petits','Pas de restriction','picture1.jpg','movie.avi'),
(34,1,1,'Pirates of the Caribbean','pirates-of-caribbean','Les visiteurs peuvent etre eclabousses','Pas de restriction','picture1.jpg','movie.avi'),
(35,1,3,'Rencontre avec Mickey','rencontre-avec-myckey','Divertissement pour les plus petits.','Pas de restriction','picture1.jpg','movie.avi'),
(36,1,4,'Rustler Roundup Shootin','rustler-roundup-shootin','Aventure en Famille','Pas de restriction','picture1.jpg','movie.avi'),
(37,1,1,'Star Tours - l\'Aventure Continue','start-tours','Grands frissons','Taille: 1,02m','picture1.jpg','movie.avi'),
(38,1,2,'Star Wars Hyperspace Mountain','star-wars-hyperspace-mountain','Grands frissons','Taille: 1,20m','picture1.jpg','movie.avi'),
(39,1,2,'Starport - rencontre avec un Personnage StarWars','startport','Rencontrez un personnage StarWars','Pas de restriction','picture1.jpg','movie.avi'),
(40,1,4,'Thunder Mesa Riverboat Landing','thunder-mesa-riverboat-landing','Promenades relaxantes','Pas de restriction','picture1.jpg','movie.avi'),
(41,1,3,'CaseyJr – le Petit Train du Cirque','casy-jr-le-petit-train-du-cirque','Divertissement pour les plus petits','Pas de restriction','picture1.jpg','movie.avi'),
(42,2,6,'Animation Academy','animation-academy','Divertissement pour les plus petits','Pas de restriction','picture42.jpg','movie42.avi'),
(43,2,7,'Avengers Assemble : Flight Force','avengers-assemble-flight-force','Grands frissons, à ne pas rater','Taille: 1,20m','picture43.jpg','movie43.avi'),
(44,2,8,'Cars Quatre Roues Rallye','cars-quatre-roues-rally','Divertissement pour les plus petits','Pas de restriction','picture44.jpg','movie44.avi'),
(45,2,8,'Cars ROAD TRIP','cars-road-trip','Aventure en famille, les visiteurs peuvent être éclaboussés','Pas de restriction','picture45.jpg','movie45.avi'),
(46,2,8,'Crush\'s Coaster','crush-s-coaster','Grands frissons','Taille: 1.07m','picture46.jpg','movie46.avi'),
(47,2,9,'Disney Studio 1','disney-studio-1','Aventure','Pas de restriction','picture47.jpg','movie47.avi'),
(48,2,6,'Les Tapis Volants – Flying Carpets Over Agrabah','les-tapis-volants','Divertissement pour les plus petits','Pas de restriction','picture48.jpg','movie48.avi'),
(49,2,8,'RC Racer','rc-racer','Grands frissons','Taille: 1,20m','picture49.jpg','movie49.avi'),
(50,2,8,'Ratatouille: L\'Aventure Toquée de Rémy','ratatouille','Divertissement pour les plus petits','Pas de restriction','picture50.jpg','movie50.avi'),
(51,2,8,'Slinky Dog Zigzag Spin','slinky-dog-zigzag-spin','Divertissement pour les plus petits','Pas de restriction','picture51.jpg','movie51.avi'),
(52,2,7,'Spider-Man W.E.B. Adventure','spider-man-web-aventure','Aventure en famille','Pas de restriction','picture52.jpg','movie52.jpg'),
(53,2,10,'The Twilight Zone Tower of Terror','the-twilight-zone-tower-of-terror','Grands frissons','Taille: 1,02m','picture53.jpg','movie53.avi'),
(54,2,8,'Toy Soldiers Parachute Drop','toy-soldiers-parachutes-drop','Aventure en famille','Taille: 0,87m','picture54.jpg','movie54.avi');
